INSERT INTO CATEGORY VALUES(1, 'Comic Books');
INSERT INTO CATEGORY  VALUES(2, 'Movies');
INSERT INTO CATEGORY VALUES(3, 'Books');

INSERT INTO SUPPLIER (id, name) VALUES (1, 'Panini Comics');
INSERT INTO SUPPLIER  (id, name) VALUES (2, 'Amazon');

INSERT INTO PRODUCT (id, name, ID_SUPPLIER, ID_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (1, 'Crise nas inifintas Terras', 1, 1, 10, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (id, name, ID_SUPPLIER, ID_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT)  VALUES (2, 'CriseInterestelar', 2, 2, 5, CURRENT_TIMESTAMP);

INSERT INTO PRODUCT (id, name, ID_SUPPLIER, ID_CATEGORY, QUANTITY_AVAILABLE, CREATED_AT) VALUES (3, 'Harry Potter E A Pedra Filosofal', 2, 3, 3, CURRENT_TIMESTAMP);